import { ArrowRightIcon, LockClosedIcon, TruckIcon } from "@heroicons/react/24/outline";
import Image from "next/image";
import Link from "next/link";
import { ProductCard } from "@/components/store/ProductCard";
import { getFeaturedProducts } from "@/lib/commerce/products";

const benefits=[{Icon:TruckIcon,title:"Entrega nacional",description:"Acompanhe a sua encomenda"},{Icon:LockClosedIcon,title:"Pagamento protegido",description:"M‑Pesa, e‑Mola e outros métodos"},{Icon:ArrowRightIcon,title:"Apoio simples",description:"Ajuda antes e depois da compra"}];
export default async function Home(){const products=await getFeaturedProducts();return <>
  <section className="container py-6"><div className="relative min-h-[560px] overflow-hidden rounded-2xl bg-neutral-100"><Image src="https://images.unsplash.com/photo-1607082349566-187342175e2f?auto=format&fit=crop&w=1600&q=80" alt="Colecção Inevia.shop" fill priority className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-black/75 via-black/35 to-transparent"/><div className="relative flex min-h-[560px] max-w-xl flex-col justify-center p-8 text-white md:p-14"><p className="text-xs font-bold uppercase tracking-[.2em]">Colecção 2026</p><h1 className="mt-4 text-4xl font-black leading-[1.05] tracking-tight md:text-6xl">Uma nova forma de comprar.</h1><p className="mt-5 max-w-md text-base leading-7 text-neutral-200">Produtos seleccionados, pagamentos locais e entrega segura em Moçambique.</p><div className="mt-8"><Link href="/produtos" className="btn btn-primary">Comprar agora <ArrowRightIcon className="h-4 w-4"/></Link></div></div></div></section>
  <section className="container py-14"><div className="flex items-end justify-between border-b border-neutral-200 pb-5"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-neutral-500">Escolhas Inevia</p><h2 className="mt-2 text-3xl font-black tracking-tight">Produtos em destaque</h2></div><Link href="/produtos" className="hidden items-center gap-1 text-sm font-semibold hover:text-green-700 sm:flex">Ver todos <ArrowRightIcon className="h-4 w-4"/></Link></div><div className="mt-8 grid grid-cols-2 gap-x-4 gap-y-10 md:grid-cols-4">{products.map(p=><ProductCard key={p.id} p={p}/>)}</div></section>
  <section className="border-y border-neutral-200 bg-white"><div className="container grid divide-y divide-neutral-200 md:grid-cols-3 md:divide-x md:divide-y-0">{benefits.map(({Icon,title,description})=><div className="flex items-center gap-4 px-4 py-8 first:pl-0" key={title}><Icon className="h-7 w-7 text-neutral-900"/><div><h3 className="text-sm font-bold">{title}</h3><p className="mt-1 text-xs text-neutral-500">{description}</p></div></div>)}</div></section>
  </>}
