"use client";

import { Field, Label, Radio, RadioGroup } from "@headlessui/react";
import { CheckIcon, ChevronLeftIcon, LockClosedIcon } from "@heroicons/react/24/outline";
import { useState } from "react";
import { money } from "@/lib/catalog";

const steps=["Cliente","Entrega","Pagamento"];
const methods=[{value:"MPESA",title:"M‑Pesa",description:"Confirme o pagamento no telemóvel"},{value:"EMOLA",title:"e‑Mola",description:"Pagamento móvel rápido e seguro"},{value:"BANK_TRANSFER",title:"Transferência bancária",description:"Dados apresentados após o pedido"},{value:"CASH_ON_DELIVERY",title:"Pagamento na entrega",description:"Pague quando receber a encomenda"}];

export function CheckoutForm(){const [step,setStep]=useState(0);const [method,setMethod]=useState("MPESA");return <div>
  <ol className="mb-10 flex border-b border-neutral-200" aria-label="Progresso do checkout">{steps.map((label,index)=><li key={label} className={`flex-1 border-b-2 pb-4 text-xs font-bold uppercase tracking-wider ${index<=step?"border-green-600 text-neutral-950":"border-transparent text-neutral-400"}`}>{index+1}. {label}</li>)}</ol>
  <section><h1 className="text-2xl font-black tracking-tight">{steps[step]}</h1>
    {step===0&&<div className="mt-7 grid gap-5 md:grid-cols-2"><div className="md:col-span-2"><label htmlFor="email">E-mail</label><input id="email" type="email" autoComplete="email" className="mt-2"/></div><div><label htmlFor="first">Nome</label><input id="first" autoComplete="given-name" className="mt-2"/></div><div><label htmlFor="last">Apelido</label><input id="last" autoComplete="family-name" className="mt-2"/></div><div className="md:col-span-2"><label htmlFor="phone">Telefone</label><input id="phone" autoComplete="tel" placeholder="+258 84 000 0000" className="mt-2"/></div></div>}
    {step===1&&<div className="mt-7 grid gap-5 md:grid-cols-2"><div className="md:col-span-2"><label htmlFor="address">Morada</label><input id="address" autoComplete="street-address" className="mt-2"/></div><div><label htmlFor="city">Cidade</label><select id="city" className="mt-2"><option>Maputo</option><option>Matola</option><option>Beira</option><option>Nampula</option></select></div><div><label htmlFor="province">Província</label><input id="province" className="mt-2"/></div><label className="md:col-span-2 flex cursor-pointer items-start gap-3 rounded-lg border-2 border-green-600 p-4"><input type="radio" defaultChecked className="!mt-1 !w-auto accent-green-600"/><span><strong className="text-sm">Entrega normal</strong><small className="block text-neutral-500">2–4 dias úteis</small></span><strong className="ml-auto text-sm">250 MT</strong></label></div>}
    {step===2&&<RadioGroup value={method} onChange={setMethod} className="mt-7 space-y-3" aria-label="Método de pagamento">{methods.map(option=><Field key={option.value}><Radio value={option.value} className="group flex cursor-pointer items-center rounded-lg border border-neutral-300 p-4 data-checked:border-green-600 data-checked:ring-1 data-checked:ring-green-600"><span className="mr-4 grid h-5 w-5 place-items-center rounded-full border border-neutral-400 group-data-checked:border-green-600 group-data-checked:bg-green-600"><CheckIcon className="h-3.5 w-3.5 text-white opacity-0 group-data-checked:opacity-100"/></span><span><Label className="cursor-pointer text-sm font-bold">{option.title}</Label><span className="block text-xs text-neutral-500">{option.description}</span></span></Radio></Field>)}</RadioGroup>}
    <div className="mt-9 flex items-center justify-between border-t border-neutral-200 pt-6">{step>0?<button className="inline-flex items-center gap-1 text-sm font-semibold" onClick={()=>setStep(value=>value-1)}><ChevronLeftIcon className="h-4 w-4"/>Voltar</button>:<span/>}<button className="btn btn-primary min-w-40" onClick={()=>step<2?setStep(value=>value+1):alert(`Pedido de ${money(9720)} pronto para confirmação por ${method}.`)}>{step<2?"Continuar":"Confirmar pedido"}</button></div>
    <p className="mt-6 flex items-center justify-center gap-2 text-xs text-neutral-500"><LockClosedIcon className="h-4 w-4"/>Os seus dados são transmitidos com segurança.</p>
  </section>
</div>}
